#!/usr/bin/env bash
# Bash script that gives you information about the holbertonschool file.
name="holbertonschool"
if [ -a $name ];
    then
        echo "$name file exists"
    if [ -s $name ];
        then
            echo "$name file is not empty"
    else
        echo "$name file is empty"
    fi
    if [ -f $name ];
        then
            echo "$name is a regular file"
    fi
else
    echo "$name file does not exist"
fi