#!/usr/bin/env bash
# Bash script that replace localhost and facebook.com IP an Ubuntu server.
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts

