#!/usr/bin/env bash
# Fix container so that Nginx is running as the nginx user
pkill -9 apache2
chmod 644 /etc/nginx/nginx.conf
chown -R nginx /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
